<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ieire</name>
   <tag></tag>
   <elementGuidId>c297a966-df37-49e1-9afa-51fd6f3ddd1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-sm.d-none.d-lg-inline-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/div[3]/div/section/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Ieșire&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a9f777f-a466-4f3b-805b-2c1f7b42ff36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm d-none d-lg-inline-block</value>
      <webElementGuid>cc5b5d99-6f5a-496c-8fa1-cc511664b589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1a854c82-6294-416f-a90d-d8b0f78707de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ieșire</value>
      <webElementGuid>f408f91c-fb73-43b2-9a30-67ed1af9c95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MainLayout__MainLayoutWrapper-sc-4yq4s6-0 ciepyG&quot;]/section[@class=&quot;handheld-toolbar-enabled&quot;]/div[@class=&quot;container pb-5 mb-2 mb-md-4&quot;]/div[@class=&quot;row&quot;]/section[@class=&quot;col-lg-8&quot;]/div[@class=&quot;d-none d-lg-flex justify-content-end align-items-center pt-lg-3 pb-4 pb-lg-5 mb-lg-3&quot;]/a[@class=&quot;btn btn-primary btn-sm d-none d-lg-inline-block&quot;]</value>
      <webElementGuid>bb1b2fcc-4509-4f72-aa89-c36a9fdf042f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div[3]/div/section/div/a</value>
      <webElementGuid>bfdb3b7c-3a2e-42ba-8178-afecc8fdfc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ieșire')])[2]</value>
      <webElementGuid>57cec33a-5034-4a0d-aeb6-39a4d6229529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informații profil'])[2]/following::a[2]</value>
      <webElementGuid>c76c237b-134a-4b74-b8ac-be849747a98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informații'])[1]/preceding::a[1]</value>
      <webElementGuid>568b8e9d-0562-4708-ba73-6143925eea7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand-uri'])[1]/preceding::a[1]</value>
      <webElementGuid>24bbf63e-951f-461b-ba41-e1ee92b62f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>c070abb3-f8a3-4d5e-a2b8-ffd0112069e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/a</value>
      <webElementGuid>e195711d-f574-4b7e-9cbc-135ed16f9e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Ieșire' or . = 'Ieșire')]</value>
      <webElementGuid>19fc1a03-6954-4c46-a6e1-12bceac6ef6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
