<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Favorite_navbar-tool-icon ci-user</name>
   <tag></tag>
   <elementGuidId>606a29f5-cdca-41d6-a684-944181ba4f8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.navbar-tool-icon.ci-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar']/div/div/div/div[2]/a[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fdb1612d-c864-4e51-a56f-a1af879ba120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-tool-icon ci-user</value>
      <webElementGuid>038fe676-986a-4562-874c-b6190b50da41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;navbar-sticky bg-light&quot;]/div[@class=&quot;navbar navbar-expand-lg navbar-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;navbar-toolbar d-flex flex-shrink-0 align-items-center&quot;]/a[@class=&quot;navbar-tool&quot;]/div[@class=&quot;navbar-tool-icon-box&quot;]/i[@class=&quot;navbar-tool-icon ci-user&quot;]</value>
      <webElementGuid>24dc368d-b055-4c47-9b66-35eeab7cdea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/div/div/div[2]/a[3]/div/i</value>
      <webElementGuid>55579cf0-459e-48ab-9fc4-f5c7fe03bacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div/i</value>
      <webElementGuid>565b3e95-c6ca-4b6f-87ee-bc1a4a94e93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
